# Generated by Django 2.2.6 on 2020-07-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0002_auto_20200716_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='eballot_no',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
