# Generated by Django 2.2.6 on 2020-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0004_auto_20200718_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='eballot_no',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
